import { Shipment } from "@entities/shipment";

export const shipments: Shipment[] = [
  {
    customerName: "НТО Консалт",
    id: "TXE-45821",
    origin: "Tashkent",
    destination: "Almaty",
    status: "В пути",
    vehicleNumber: "TRK-22",
    vehicleId: "VEH-01",
    estimatedArrival: "3h 20m",
    createdDate: "2026-03-10",
    driverName: "John Smith",
    driverPhone: "+998 90 120 44 11",
    cargoType: "Textile rolls",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "12.8 t",
    progress: 72,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45822",
    origin: "Samarkand",
    destination: "Shymkent",
    status: "На границе",
    vehicleNumber: "TRK-07",
    vehicleId: "VEH-02",
    estimatedArrival: "6h 15m",
    createdDate: "2026-03-10",
    driverName: "Aleksei Voronin",
    driverPhone: "+998 93 221 77 30",
    cargoType: "Industrial valves",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "9.2 t",
    progress: 54,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45823",
    origin: "Bukhara",
    destination: "Bishkek",
    status: "Задерживается",
    vehicleNumber: "TRK-19",
    vehicleId: "VEH-03",
    estimatedArrival: "9h 10m",
    createdDate: "2026-03-09",
    driverName: "Nurlan Bekov",
    driverPhone: "+996 555 311 880",
    cargoType: "Warehouse shelving",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "15.4 t",
    progress: 41,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45824",
    origin: "Tashkent",
    destination: "Astana",
    status: "Таможенный контроль",
    vehicleNumber: "TRK-31",
    vehicleId: "VEH-04",
    estimatedArrival: "14h 40m",
    createdDate: "2026-03-09",
    driverName: "Dmitry Sokolov",
    driverPhone: "+7 705 833 99 12",
    cargoType: "Auto parts",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "11.6 t",
    progress: 38,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45825",
    origin: "Andijan",
    destination: "Almaty",
    status: "Прибывает",
    vehicleNumber: "TRK-11",
    vehicleId: "VEH-05",
    estimatedArrival: "1h 30m",
    createdDate: "2026-03-11",
    driverName: "Azamat Rakhimov",
    driverPhone: "+998 91 345 09 76",
    cargoType: "Consumer electronics",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "7.1 t",
    progress: 88,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45826",
    origin: "Navoi",
    destination: "Karaganda",
    status: "В пути",
    vehicleNumber: "TRK-44",
    vehicleId: "VEH-06",
    estimatedArrival: "11h 05m",
    createdDate: "2026-03-08",
    driverName: "Ruslan Dzhuraev",
    driverPhone: "+998 97 488 11 63",
    cargoType: "Copper coils",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "17.2 t",
    progress: 49,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45827",
    origin: "Tashkent",
    destination: "Dushanbe",
    status: "В пути",
    vehicleNumber: "TRK-13",
    vehicleId: "VEH-07",
    estimatedArrival: "5h 45m",
    createdDate: "2026-03-11",
    driverName: "Bahrom Yuldashev",
    driverPhone: "+992 901 551 440",
    cargoType: "Medical supplies",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "4.8 t",
    progress: 63,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45828",
    origin: "Khujand",
    destination: "Tashkent",
    status: "Прибывает",
    vehicleNumber: "TRK-18",
    vehicleId: "VEH-08",
    estimatedArrival: "2h 05m",
    createdDate: "2026-03-08",
    driverName: "Farhod Karimov",
    driverPhone: "+992 918 370 111",
    cargoType: "Retail inventory",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "6.9 t",
    progress: 82,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45829",
    origin: "Almaty",
    destination: "Tashkent",
    status: "Задерживается",
    vehicleNumber: "TRK-27",
    vehicleId: "VEH-09",
    estimatedArrival: "7h 40m",
    createdDate: "2026-03-07",
    driverName: "Marat Ospanov",
    driverPhone: "+7 701 205 61 88",
    cargoType: "Packaged foods",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "10.3 t",
    progress: 57,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45830",
    origin: "Bishkek",
    destination: "Shymkent",
    status: "В пути",
    vehicleNumber: "TRK-36",
    vehicleId: "VEH-10",
    estimatedArrival: "4h 55m",
    createdDate: "2026-03-10",
    driverName: "Tilek Toktogulov",
    driverPhone: "+996 709 662 118",
    cargoType: "Household appliances",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "8.6 t",
    progress: 68,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45831",
    origin: "Samarkand",
    destination: "Baku",
    status: "Таможенный контроль",
    vehicleNumber: "TRK-51",
    vehicleId: "VEH-04",
    estimatedArrival: "22h 10m",
    createdDate: "2026-03-06",
    driverName: "Dmitry Sokolov",
    driverPhone: "+7 705 833 99 12",
    cargoType: "Construction tools",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "13.1 t",
    progress: 27,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45832",
    origin: "Tashkent",
    destination: "Tbilisi",
    status: "На границе",
    vehicleNumber: "TRK-29",
    vehicleId: "VEH-02",
    estimatedArrival: "19h 25m",
    createdDate: "2026-03-05",
    driverName: "Aleksei Voronin",
    driverPhone: "+998 93 221 77 30",
    cargoType: "IT hardware",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "5.7 t",
    progress: 35,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45833",
    origin: "Karshi",
    destination: "Aktobe",
    status: "В пути",
    vehicleNumber: "TRK-54",
    vehicleId: "VEH-06",
    estimatedArrival: "16h 50m",
    createdDate: "2026-03-04",
    driverName: "Ruslan Dzhuraev",
    driverPhone: "+998 97 488 11 63",
    cargoType: "Chemicals",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "14.6 t",
    progress: 46,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45834",
    origin: "Ferghana",
    destination: "Osh",
    status: "Доставлен",
    vehicleNumber: "TRK-63",
    vehicleId: "VEH-07",
    estimatedArrival: "Завершено",
    createdDate: "2026-03-03",
    driverName: "Bahrom Yuldashev",
    driverPhone: "+992 901 551 440",
    cargoType: "Furniture",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "9.9 t",
    progress: 100,
  },
  {
    customerName: "НТО Консалт",
    id: "TXE-45835",
    origin: "Urgench",
    destination: "Atyrau",
    status: "В пути",
    vehicleNumber: "TRK-72",
    vehicleId: "VEH-09",
    estimatedArrival: "18h 35m",
    createdDate: "2026-03-02",
    driverName: "Marat Ospanov",
    driverPhone: "+7 701 205 61 88",
    cargoType: "Agricultural equipment",
    departed: true, currentLocation: "", departureDate: "", distance: "", transportationType: null,
    weight: "16.4 t",
    progress: 33,
  },
];
